# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Side Work
email: ryanlevell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is simply to track my side work for my personal benefit.
  I very often gain/lose interest in side projects. I will now be
  able to reflect on the old work that I would otherwise forget. The
  posts will be informal notes rather than nicely formatted, well
  explained generic blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryanlevell.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: ryanlevell

# Build settings
markdown: kramdown
