# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: ryanlevell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I needed a place to keep notes while working. I very often lose/gain interest
  in random tech and would like to reflect on any old work that I would have
  otherwise forgot about.
baseurl: "/blog" # the subpath of your site
url: "http://ryanlevell.github.io" # the base hostname & protocol for your site
github_username:  ryanlevell

# Build settings
markdown: kramdown
